name: Pull Request

run-name: "${{ github.actor }} abriu ou atualizou um Pull Request"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-iac:
    name: Check IaC
    runs-on: ubuntu-24.04

    steps:
      - name: Obter o código
        uses: actions/checkout@v7.0.1

      - name: Analisar configurações com Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: "1"
          severity: HIGH,CRITICAL
