name: GitHub Actions Pull Request
run-name: ${{ github.actor }} is testing out GitHub Actions for PR 🚀
on: 
  pull_request:
jobs:
  check_iac:
    name: Check IaC for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          hide-progress: 'true'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
